# Generated by Django 5.0 on 2026-01-19 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentGatewayConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway_type', models.CharField(choices=[('moyasar', 'Moyasar'), ('hyperpay', 'HyperPay'), ('stripe', 'Stripe')], max_length=20, unique=True, verbose_name='نوع البوابة')),
                ('api_key', models.CharField(max_length=255, verbose_name='API Key')),
                ('api_secret', models.CharField(blank=True, max_length=255, verbose_name='API Secret')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('is_test_mode', models.BooleanField(default=True, verbose_name='وضع الاختبار')),
            ],
            options={
                'verbose_name': 'إعدادات بوابة دفع',
                'verbose_name_plural': 'إعدادات بوابات الدفع',
                'db_table': 'payment_gateway_configs',
            },
        ),
    ]
