# Generated by Django 5.0 on 2026-01-21 04:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('insurance_core', '0002_insuranceservice_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='معرف الجلسة')),
                ('user_identifier', models.CharField(db_index=True, help_text='رقم الهاتف أو معرف فريد', max_length=50, verbose_name='معرف المستخدم')),
                ('channel', models.CharField(choices=[('whatsapp', 'واتساب'), ('web_chat', 'محادثة الويب'), ('api', 'API'), ('mobile_app', 'تطبيق الجوال')], default='whatsapp', max_length=20, verbose_name='قناة التواصل')),
                ('status', models.CharField(choices=[('active', 'نشطة'), ('completed', 'مكتملة'), ('abandoned', 'متروكة'), ('expired', 'منتهية'), ('cancelled', 'ملغاة')], db_index=True, default='active', max_length=20, verbose_name='حالة الجلسة')),
                ('current_stage', models.CharField(choices=[('greeting', 'الترحيب'), ('service_details', 'تفاصيل الخدمة'), ('collecting_vehicle', 'جمع بيانات السيارة'), ('confirming_vehicle', 'تأكيد بيانات السيارة'), ('showing_offers', 'عرض العروض'), ('offer_details', 'تفاصيل العرض'), ('collecting_profile', 'جمع بيانات العميل'), ('confirming_profile', 'تأكيد بيانات العميل'), ('order_summary', 'ملخص الطلب'), ('confirmation', 'التأكيد النهائي'), ('payment_pending', 'انتظار الدفع'), ('completed', 'مكتمل')], default='greeting', max_length=30, verbose_name='المرحلة الحالية')),
                ('previous_stage', models.CharField(blank=True, choices=[('greeting', 'الترحيب'), ('service_details', 'تفاصيل الخدمة'), ('collecting_vehicle', 'جمع بيانات السيارة'), ('confirming_vehicle', 'تأكيد بيانات السيارة'), ('showing_offers', 'عرض العروض'), ('offer_details', 'تفاصيل العرض'), ('collecting_profile', 'جمع بيانات العميل'), ('confirming_profile', 'تأكيد بيانات العميل'), ('order_summary', 'ملخص الطلب'), ('confirmation', 'التأكيد النهائي'), ('payment_pending', 'انتظار الدفع'), ('completed', 'مكتمل')], max_length=30, null=True, verbose_name='المرحلة السابقة')),
                ('message_count', models.PositiveIntegerField(default=0, verbose_name='عدد الرسائل')),
                ('stage_transitions_count', models.PositiveIntegerField(default=0, verbose_name='عدد الانتقالات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('last_activity_at', models.DateTimeField(auto_now=True, verbose_name='آخر نشاط')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الاكتمال')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الانتهاء')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='بيانات إضافية')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversation_sessions', to='insurance_core.insuranceorder', verbose_name='الطلب الناتج')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversation_sessions', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم المسجل')),
            ],
            options={
                'verbose_name': 'جلسة محادثة',
                'verbose_name_plural': 'جلسات المحادثات',
                'db_table': 'conversation_sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConversationMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='معرف الرسالة')),
                ('role', models.CharField(choices=[('user', 'المستخدم'), ('assistant', 'المساعد'), ('system', 'النظام')], max_length=20, verbose_name='الدور')),
                ('message_type', models.CharField(choices=[('text', 'نص'), ('image', 'صورة'), ('document', 'مستند'), ('location', 'موقع'), ('button_response', 'رد زر'), ('list_response', 'رد قائمة')], default='text', max_length=20, verbose_name='نوع الرسالة')),
                ('content', models.TextField(verbose_name='المحتوى')),
                ('stage_at_message', models.CharField(choices=[('greeting', 'الترحيب'), ('service_details', 'تفاصيل الخدمة'), ('collecting_vehicle', 'جمع بيانات السيارة'), ('confirming_vehicle', 'تأكيد بيانات السيارة'), ('showing_offers', 'عرض العروض'), ('offer_details', 'تفاصيل العرض'), ('collecting_profile', 'جمع بيانات العميل'), ('confirming_profile', 'تأكيد بيانات العميل'), ('order_summary', 'ملخص الطلب'), ('confirmation', 'التأكيد النهائي'), ('payment_pending', 'انتظار الدفع'), ('completed', 'مكتمل')], max_length=30, verbose_name='المرحلة')),
                ('extracted_data', models.JSONField(blank=True, null=True, verbose_name='البيانات المستخرجة')),
                ('ai_analysis', models.JSONField(blank=True, null=True, verbose_name='تحليل AI')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإرسال')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='بيانات إضافية')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='insurance_ai.conversationsession', verbose_name='الجلسة')),
            ],
            options={
                'verbose_name': 'رسالة محادثة',
                'verbose_name_plural': 'رسائل المحادثات',
                'db_table': 'conversation_messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='SessionAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_duration_seconds', models.PositiveIntegerField(default=0, verbose_name='المدة الإجمالية (ثواني)')),
                ('active_duration_seconds', models.PositiveIntegerField(default=0, verbose_name='مدة النشاط (ثواني)')),
                ('user_messages_count', models.PositiveIntegerField(default=0, verbose_name='رسائل المستخدم')),
                ('assistant_messages_count', models.PositiveIntegerField(default=0, verbose_name='رسائل المساعد')),
                ('avg_response_time_seconds', models.FloatField(blank=True, null=True, verbose_name='متوسط وقت الرد')),
                ('stages_visited', models.JSONField(default=list, verbose_name='المراحل المزارة')),
                ('time_per_stage', models.JSONField(default=dict, verbose_name='الوقت لكل مرحلة')),
                ('drop_off_stage', models.CharField(blank=True, choices=[('greeting', 'الترحيب'), ('service_details', 'تفاصيل الخدمة'), ('collecting_vehicle', 'جمع بيانات السيارة'), ('confirming_vehicle', 'تأكيد بيانات السيارة'), ('showing_offers', 'عرض العروض'), ('offer_details', 'تفاصيل العرض'), ('collecting_profile', 'جمع بيانات العميل'), ('confirming_profile', 'تأكيد بيانات العميل'), ('order_summary', 'ملخص الطلب'), ('confirmation', 'التأكيد النهائي'), ('payment_pending', 'انتظار الدفع'), ('completed', 'مكتمل')], max_length=30, null=True, verbose_name='مرحلة التوقف')),
                ('ai_confidence_avg', models.FloatField(blank=True, null=True, verbose_name='متوسط ثقة AI')),
                ('extraction_accuracy', models.FloatField(blank=True, null=True, verbose_name='دقة الاستخراج')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='insurance_ai.conversationsession', verbose_name='الجلسة')),
            ],
            options={
                'verbose_name': 'تحليلات جلسة',
                'verbose_name_plural': 'تحليلات الجلسات',
                'db_table': 'session_analytics',
            },
        ),
        migrations.CreateModel(
            name='SessionOffersData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shown_offers', models.JSONField(default=list, verbose_name='العروض المعروضة')),
                ('shown_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ العرض')),
                ('selected_offer_data', models.JSONField(blank=True, null=True, verbose_name='بيانات العرض المختار')),
                ('selected_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الاختيار')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='تم تأكيد العرض')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ التأكيد')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('selected_offer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session_selections', to='insurance_core.insuranceoffer', verbose_name='العرض المختار')),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='offers_data', to='insurance_ai.conversationsession', verbose_name='الجلسة')),
            ],
            options={
                'verbose_name': 'عروض الجلسة',
                'verbose_name_plural': 'عروض الجلسات',
                'db_table': 'session_offers_data',
            },
        ),
        migrations.CreateModel(
            name='SessionProfileData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_id', models.CharField(blank=True, max_length=10, null=True, verbose_name='رقم الهوية')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الميلاد')),
                ('full_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='الاسم الكامل')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='رقم الجوال')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='البريد الإلكتروني')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='المدينة')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='تم التأكيد')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ التأكيد')),
                ('is_complete', models.BooleanField(default=False, verbose_name='البيانات مكتملة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile_data', to='insurance_ai.conversationsession', verbose_name='الجلسة')),
            ],
            options={
                'verbose_name': 'بيانات عميل الجلسة',
                'verbose_name_plural': 'بيانات عملاء الجلسات',
                'db_table': 'session_profile_data',
            },
        ),
        migrations.CreateModel(
            name='SessionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_order_created', models.BooleanField(default=False, verbose_name='تم إنشاء الطلب')),
                ('is_invoice_created', models.BooleanField(default=False, verbose_name='تم إنشاء الفاتورة')),
                ('is_payment_completed', models.BooleanField(default=False, verbose_name='تم الدفع')),
                ('is_policy_issued', models.BooleanField(default=False, verbose_name='تم إصدار الوثيقة')),
                ('order_created_at', models.DateTimeField(blank=True, null=True)),
                ('invoice_created_at', models.DateTimeField(blank=True, null=True)),
                ('payment_completed_at', models.DateTimeField(blank=True, null=True)),
                ('policy_issued_at', models.DateTimeField(blank=True, null=True)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='المبلغ الإجمالي')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session_results', to='insurance_core.invoice', verbose_name='الفاتورة')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session_results', to='insurance_core.insuranceorder', verbose_name='الطلب')),
                ('policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session_results', to='insurance_core.policy', verbose_name='الوثيقة')),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='insurance_ai.conversationsession', verbose_name='الجلسة')),
            ],
            options={
                'verbose_name': 'نتيجة جلسة',
                'verbose_name_plural': 'نتائج الجلسات',
                'db_table': 'session_results',
            },
        ),
        migrations.CreateModel(
            name='SessionVehicleData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(blank=True, max_length=100, null=True, verbose_name='الماركة')),
                ('model', models.CharField(blank=True, max_length=100, null=True, verbose_name='الموديل')),
                ('year', models.PositiveIntegerField(blank=True, null=True, verbose_name='سنة الصنع')),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='القيمة')),
                ('plate_no', models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم اللوحة')),
                ('service_type', models.CharField(blank=True, help_text='comprehensive أو tpl', max_length=20, null=True, verbose_name='نوع التأمين')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='تم التأكيد')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ التأكيد')),
                ('is_complete', models.BooleanField(default=False, verbose_name='البيانات مكتملة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_data', to='insurance_ai.conversationsession', verbose_name='الجلسة')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session_data', to='insurance_core.vehicle', verbose_name='المركبة المسجلة')),
            ],
            options={
                'verbose_name': 'بيانات سيارة الجلسة',
                'verbose_name_plural': 'بيانات سيارات الجلسات',
                'db_table': 'session_vehicle_data',
            },
        ),
        migrations.CreateModel(
            name='StageTransition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_stage', models.CharField(choices=[('greeting', 'الترحيب'), ('service_details', 'تفاصيل الخدمة'), ('collecting_vehicle', 'جمع بيانات السيارة'), ('confirming_vehicle', 'تأكيد بيانات السيارة'), ('showing_offers', 'عرض العروض'), ('offer_details', 'تفاصيل العرض'), ('collecting_profile', 'جمع بيانات العميل'), ('confirming_profile', 'تأكيد بيانات العميل'), ('order_summary', 'ملخص الطلب'), ('confirmation', 'التأكيد النهائي'), ('payment_pending', 'انتظار الدفع'), ('completed', 'مكتمل')], max_length=30, verbose_name='من مرحلة')),
                ('to_stage', models.CharField(choices=[('greeting', 'الترحيب'), ('service_details', 'تفاصيل الخدمة'), ('collecting_vehicle', 'جمع بيانات السيارة'), ('confirming_vehicle', 'تأكيد بيانات السيارة'), ('showing_offers', 'عرض العروض'), ('offer_details', 'تفاصيل العرض'), ('collecting_profile', 'جمع بيانات العميل'), ('confirming_profile', 'تأكيد بيانات العميل'), ('order_summary', 'ملخص الطلب'), ('confirmation', 'التأكيد النهائي'), ('payment_pending', 'انتظار الدفع'), ('completed', 'مكتمل')], max_length=30, verbose_name='إلى مرحلة')),
                ('trigger_type', models.CharField(help_text='user_input, ai_decision, system, timeout', max_length=50, verbose_name='نوع المحفز')),
                ('is_successful', models.BooleanField(default=True, verbose_name='ناجح')),
                ('failure_reason', models.TextField(blank=True, null=True, verbose_name='سبب الفشل')),
                ('data_snapshot', models.JSONField(default=dict, verbose_name='لقطة البيانات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الانتقال')),
                ('duration_seconds', models.PositiveIntegerField(blank=True, help_text='الوقت المستغرق في المرحلة السابقة', null=True, verbose_name='المدة بالثواني')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_transitions', to='insurance_ai.conversationsession', verbose_name='الجلسة')),
                ('trigger_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_transitions', to='insurance_ai.conversationmessage', verbose_name='الرسالة المحفزة')),
            ],
            options={
                'verbose_name': 'انتقال مرحلة',
                'verbose_name_plural': 'انتقالات المراحل',
                'db_table': 'stage_transitions',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='conversationsession',
            index=models.Index(fields=['session_id'], name='conversatio_session_376463_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationsession',
            index=models.Index(fields=['user_identifier'], name='conversatio_user_id_d53e74_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationsession',
            index=models.Index(fields=['status', 'current_stage'], name='conversatio_status_ab0d34_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationsession',
            index=models.Index(fields=['-last_activity_at'], name='conversatio_last_ac_4d6f9b_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationsession',
            index=models.Index(fields=['channel', 'status'], name='conversatio_channel_85c56b_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationmessage',
            index=models.Index(fields=['session', 'created_at'], name='conversatio_session_d7c9a5_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationmessage',
            index=models.Index(fields=['role'], name='conversatio_role_89de84_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationmessage',
            index=models.Index(fields=['stage_at_message'], name='conversatio_stage_a_05e6b4_idx'),
        ),
        migrations.AddIndex(
            model_name='stagetransition',
            index=models.Index(fields=['session', 'created_at'], name='stage_trans_session_9d76c9_idx'),
        ),
        migrations.AddIndex(
            model_name='stagetransition',
            index=models.Index(fields=['from_stage', 'to_stage'], name='stage_trans_from_st_611d45_idx'),
        ),
    ]
