# Generated by Django 5.0 on 2026-01-21 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_ai', '0001_add_conversation_session_models'),
    ]

    operations = [
        # إضافة نموذج SessionModificationEvent
        migrations.CreateModel(
            name='SessionModificationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(
                    choices=[
                        ('cancel', 'إلغاء كامل'),
                        ('edit_vehicle', 'تعديل بيانات السيارة'),
                        ('edit_profile', 'تعديل البيانات الشخصية'),
                        ('change_offer', 'تغيير العرض'),
                        ('go_back', 'رجوع للخطوة السابقة'),
                        ('restart', 'إعادة البدء'),
                    ],
                    max_length=20,
                    verbose_name='نوع الحدث'
                )),
                ('stage_at_event', models.CharField(
                    choices=[
                        ('greeting', 'الترحيب'),
                        ('service_details', 'تفاصيل الخدمة'),
                        ('collecting_vehicle', 'جمع بيانات السيارة'),
                        ('confirming_vehicle', 'تأكيد بيانات السيارة'),
                        ('showing_offers', 'عرض العروض'),
                        ('offer_details', 'تفاصيل العرض'),
                        ('collecting_profile', 'جمع بيانات العميل'),
                        ('confirming_profile', 'تأكيد بيانات العميل'),
                        ('order_summary', 'ملخص الطلب'),
                        ('confirmation', 'التأكيد النهائي'),
                        ('payment_pending', 'انتظار الدفع'),
                        ('completed', 'مكتمل'),
                    ],
                    max_length=30,
                    verbose_name='المرحلة عند الحدث'
                )),
                ('target_stage', models.CharField(
                    choices=[
                        ('greeting', 'الترحيب'),
                        ('service_details', 'تفاصيل الخدمة'),
                        ('collecting_vehicle', 'جمع بيانات السيارة'),
                        ('confirming_vehicle', 'تأكيد بيانات السيارة'),
                        ('showing_offers', 'عرض العروض'),
                        ('offer_details', 'تفاصيل العرض'),
                        ('collecting_profile', 'جمع بيانات العميل'),
                        ('confirming_profile', 'تأكيد بيانات العميل'),
                        ('order_summary', 'ملخص الطلب'),
                        ('confirmation', 'التأكيد النهائي'),
                        ('payment_pending', 'انتظار الدفع'),
                        ('completed', 'مكتمل'),
                    ],
                    max_length=30,
                    verbose_name='المرحلة المستهدفة'
                )),
                ('data_before', models.JSONField(default=dict, verbose_name='البيانات قبل التعديل')),
                ('data_after', models.JSONField(default=dict, verbose_name='البيانات بعد التعديل')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='سبب التعديل')),
                ('trigger_message', models.TextField(blank=True, null=True, verbose_name='رسالة المستخدم')),
                ('system_response', models.TextField(blank=True, null=True, verbose_name='رد النظام')),
                ('is_successful', models.BooleanField(default=True, verbose_name='نجح التعديل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الحدث')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='بيانات إضافية')),
                ('session', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='modification_events',
                    to='insurance_ai.conversationsession',
                    verbose_name='الجلسة'
                )),
            ],
            options={
                'verbose_name': 'حدث تعديل',
                'verbose_name_plural': 'أحداث التعديل',
                'db_table': 'session_modification_events',
                'ordering': ['-created_at'],
            },
        ),
        # إضافة indexes
        migrations.AddIndex(
            model_name='sessionmodificationevent',
            index=models.Index(fields=['session', '-created_at'], name='session_mod_session_idx'),
        ),
        migrations.AddIndex(
            model_name='sessionmodificationevent',
            index=models.Index(fields=['event_type'], name='session_mod_event_type_idx'),
        ),
        migrations.AddIndex(
            model_name='sessionmodificationevent',
            index=models.Index(fields=['stage_at_event'], name='session_mod_stage_idx'),
        ),
        # إضافة حقول إحصائيات التعديلات في SessionAnalytics
        migrations.AddField(
            model_name='sessionanalytics',
            name='total_modifications',
            field=models.PositiveIntegerField(default=0, verbose_name='إجمالي التعديلات'),
        ),
        migrations.AddField(
            model_name='sessionanalytics',
            name='cancel_count',
            field=models.PositiveIntegerField(default=0, verbose_name='عدد الإلغاءات'),
        ),
        migrations.AddField(
            model_name='sessionanalytics',
            name='edit_vehicle_count',
            field=models.PositiveIntegerField(default=0, verbose_name='عدد تعديلات السيارة'),
        ),
        migrations.AddField(
            model_name='sessionanalytics',
            name='edit_profile_count',
            field=models.PositiveIntegerField(default=0, verbose_name='عدد تعديلات البيانات الشخصية'),
        ),
        migrations.AddField(
            model_name='sessionanalytics',
            name='change_offer_count',
            field=models.PositiveIntegerField(default=0, verbose_name='عدد تغييرات العرض'),
        ),
        migrations.AddField(
            model_name='sessionanalytics',
            name='go_back_count',
            field=models.PositiveIntegerField(default=0, verbose_name='عدد الرجوع'),
        ),
    ]
