# Generated by Django 6.0.1 on 2026-01-21 11:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_ai', '0002_add_modification_events'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('human', 'رسالة المستخدم'), ('ai', 'رسالة المساعد'), ('system', 'رسالة النظام'), ('tool', 'استدعاء أداة')], default='human', max_length=20, verbose_name='نوع الرسالة')),
                ('content', models.TextField(verbose_name='المحتوى')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='بيانات إضافية')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'رسالة AI',
                'verbose_name_plural': 'رسائل AI',
                'db_table': 'ai_messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='اسم المحادثة')),
                ('assistant_id', models.CharField(blank=True, default='insurance-assistant', max_length=255, verbose_name='معرف المساعد')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
            ],
            options={
                'verbose_name': 'محادثة AI',
                'verbose_name_plural': 'محادثات AI',
                'db_table': 'ai_threads',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='sessionmodificationevent',
            new_name='session_mod_session_a46ad1_idx',
            old_name='session_mod_session_idx',
        ),
        migrations.RenameIndex(
            model_name='sessionmodificationevent',
            new_name='session_mod_event_t_03c2c3_idx',
            old_name='session_mod_event_type_idx',
        ),
        migrations.RenameIndex(
            model_name='sessionmodificationevent',
            new_name='session_mod_stage_a_02555d_idx',
            old_name='session_mod_stage_idx',
        ),
        migrations.AddField(
            model_name='thread',
            name='conversation_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='threads', to='insurance_ai.conversationsession', verbose_name='جلسة المحادثة'),
        ),
        migrations.AddField(
            model_name='thread',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_threads', to=settings.AUTH_USER_MODEL, verbose_name='المنشئ'),
        ),
        migrations.AddField(
            model_name='message',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_messages', to='insurance_ai.thread', verbose_name='المحادثة'),
        ),
        migrations.AddIndex(
            model_name='thread',
            index=models.Index(fields=['-created_at'], name='ai_threads_created_e62f53_idx'),
        ),
        migrations.AddIndex(
            model_name='thread',
            index=models.Index(fields=['assistant_id'], name='ai_threads_assista_acad06_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['thread', 'created_at'], name='ai_messages_thread__2c9422_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['message_type'], name='ai_messages_message_7fa2dc_idx'),
        ),
    ]
