# Generated by Django 5.0 on 2026-01-19 10:53

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_code', models.CharField(max_length=50, unique=True, verbose_name='رمز الشركة')),
                ('name_ar', models.CharField(max_length=200, verbose_name='الاسم بالعربية')),
                ('name_en', models.CharField(max_length=200, verbose_name='الاسم بالإنجليزية')),
                ('logo_url', models.URLField(blank=True, verbose_name='رابط الشعار')),
                ('rating_score', models.DecimalField(decimal_places=2, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='التقييم')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'شركة تأمين',
                'verbose_name_plural': 'شركات التأمين',
                'db_table': 'insurance_companies',
                'ordering': ['-rating_score', 'name_ar'],
            },
        ),
        migrations.CreateModel(
            name='InsuranceService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_code', models.CharField(max_length=50, unique=True, verbose_name='رمز الخدمة')),
                ('name_ar', models.CharField(max_length=200, verbose_name='الاسم بالعربية')),
                ('name_en', models.CharField(max_length=200, verbose_name='الاسم بالإنجليزية')),
                ('service_type', models.CharField(choices=[('AUTO_TPL', 'تأمين ضد الغير'), ('AUTO_COMP', 'تأمين شامل'), ('AUTO_VIP', 'تأمين VIP')], max_length=20, verbose_name='نوع الخدمة')),
                ('description', models.TextField(verbose_name='الوصف')),
            ],
            options={
                'verbose_name': 'خدمة تأمين',
                'verbose_name_plural': 'خدمات التأمين',
                'db_table': 'insurance_services',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_code', models.CharField(editable=False, max_length=20, unique=True, verbose_name='رمز المستخدم')),
                ('national_id', models.CharField(help_text='10 أرقام', max_length=10, unique=True, verbose_name='رقم الهوية الوطنية')),
                ('birth_date', models.DateField(verbose_name='تاريخ الميلاد')),
                ('age', models.IntegerField(editable=False, verbose_name='العمر')),
                ('phone', models.CharField(max_length=15, unique=True, verbose_name='رقم الجوال')),
                ('city', models.CharField(max_length=100, verbose_name='المدينة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'مستخدم',
                'verbose_name_plural': 'المستخدمون',
                'db_table': 'users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='InsuranceOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_code', models.CharField(max_length=50, unique=True, verbose_name='رمز العرض')),
                ('coverage_type', models.CharField(choices=[('tpl', 'ضد الغير'), ('comprehensive', 'شامل'), ('vip', 'VIP')], max_length=20, verbose_name='نوع التغطية')),
                ('min_age', models.IntegerField(default=18, verbose_name='الحد الأدنى للعمر')),
                ('max_age', models.IntegerField(default=70, verbose_name='الحد الأقصى للعمر')),
                ('min_vehicle_year', models.IntegerField(default=2010, verbose_name='أقدم سنة مركبة')),
                ('max_vehicle_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='أقصى قيمة للمركبة')),
                ('price_base', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='السعر الأساسي')),
                ('njm_discount_pct', models.DecimalField(decimal_places=2, default=10.0, max_digits=5, verbose_name='خصم نجم %')),
                ('vat_rate', models.DecimalField(decimal_places=2, default=15.0, max_digits=5, verbose_name='ضريبة القيمة المضافة %')),
                ('deductible_options', models.JSONField(default=list, verbose_name='خيارات التحمل')),
                ('included_features_json', models.JSONField(default=list, verbose_name='المزايا المضمنة')),
                ('optional_addons_json', models.JSONField(default=list, verbose_name='الإضافات الاختيارية')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='insurance_core.insurancecompany', verbose_name='الشركة')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='insurance_core.insuranceservice', verbose_name='الخدمة')),
            ],
            options={
                'verbose_name': 'عرض تأمين',
                'verbose_name_plural': 'عروض التأمين',
                'db_table': 'insurance_offers',
                'ordering': ['price_base'],
            },
        ),
        migrations.CreateModel(
            name='InsuranceOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_code', models.CharField(editable=False, max_length=50, unique=True, verbose_name='رمز الطلب')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='السعر الإجمالي')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('awaiting_confirmation', 'بانتظار التأكيد'), ('pending_payment', 'بانتظار الدفع'), ('paid', 'مدفوع'), ('policy_issued', 'صدرت الوثيقة'), ('cancelled', 'ملغي')], default='draft', max_length=30, verbose_name='الحالة')),
                ('has_njm_discount', models.BooleanField(default=False, verbose_name='لديه خصم نجم')),
                ('selected_deductible', models.JSONField(blank=True, null=True, verbose_name='التحمل المختار')),
                ('selected_addons', models.JSONField(default=list, verbose_name='الإضافات المختارة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='insurance_core.insuranceoffer', verbose_name='العرض')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='العميل')),
            ],
            options={
                'verbose_name': 'طلب تأمين',
                'verbose_name_plural': 'طلبات التأمين',
                'db_table': 'insurance_orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(editable=False, max_length=50, unique=True, verbose_name='رقم الفاتورة')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='المبلغ')),
                ('status', models.CharField(choices=[('pending', 'معلقة'), ('paid', 'مدفوعة'), ('expired', 'منتهية'), ('cancelled', 'ملغاة')], default='pending', max_length=20, verbose_name='الحالة')),
                ('expires_at', models.DateTimeField(verbose_name='تنتهي في')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الدفع')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='insurance_core.insuranceorder', verbose_name='الطلب')),
            ],
            options={
                'verbose_name': 'فاتورة',
                'verbose_name_plural': 'الفواتير',
                'db_table': 'invoices',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_ref', models.CharField(max_length=100, unique=True, verbose_name='رقم المعاملة')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='المبلغ')),
                ('payment_method', models.CharField(choices=[('credit_card', 'بطاقة ائتمان'), ('debit_card', 'بطاقة مدى'), ('apple_pay', 'Apple Pay'), ('stc_pay', 'STC Pay'), ('bank_transfer', 'تحويل بنكي')], max_length=50, verbose_name='طريقة الدفع')),
                ('status', models.CharField(choices=[('pending', 'معلق'), ('processing', 'قيد المعالجة'), ('completed', 'مكتمل'), ('failed', 'فشل'), ('refunded', 'مسترد')], max_length=20, verbose_name='الحالة')),
                ('gateway_response', models.JSONField(default=dict, verbose_name='استجابة البوابة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإتمام')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='insurance_core.invoice', verbose_name='الفاتورة')),
            ],
            options={
                'verbose_name': 'دفعة',
                'verbose_name_plural': 'المدفوعات',
                'db_table': 'payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_no', models.CharField(editable=False, max_length=50, unique=True, verbose_name='رقم الوثيقة')),
                ('start_date', models.DateField(verbose_name='تاريخ البداية')),
                ('end_date', models.DateField(verbose_name='تاريخ الانتهاء')),
                ('pdf_url', models.URLField(verbose_name='رابط PDF')),
                ('issued_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإصدار')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='policy', to='insurance_core.insuranceorder', verbose_name='الطلب')),
            ],
            options={
                'verbose_name': 'وثيقة تأمين',
                'verbose_name_plural': 'وثائق التأمين',
                'db_table': 'policies',
                'ordering': ['-issued_at'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_no', models.CharField(max_length=20, unique=True, verbose_name='رقم اللوحة')),
                ('brand', models.CharField(max_length=100, verbose_name='الماركة')),
                ('model', models.CharField(max_length=100, verbose_name='الموديل')),
                ('model_year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1990), django.core.validators.MaxValueValidator(2030)], verbose_name='سنة الصنع')),
                ('vehicle_value', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='قيمة المركبة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to=settings.AUTH_USER_MODEL, verbose_name='المالك')),
            ],
            options={
                'verbose_name': 'مركبة',
                'verbose_name_plural': 'المركبات',
                'db_table': 'vehicles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='insuranceorder',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='insurance_core.vehicle', verbose_name='المركبة'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['national_id'], name='users_nationa_4aa388_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['phone'], name='users_phone_af6883_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['city'], name='users_city_9c6023_idx'),
        ),
        migrations.AddIndex(
            model_name='insuranceoffer',
            index=models.Index(fields=['company', 'service'], name='insurance_o_company_a48bf5_idx'),
        ),
        migrations.AddIndex(
            model_name='insuranceoffer',
            index=models.Index(fields=['coverage_type', 'is_active'], name='insurance_o_coverag_554c92_idx'),
        ),
        migrations.AddIndex(
            model_name='insuranceoffer',
            index=models.Index(fields=['price_base'], name='insurance_o_price_b_b4b5a9_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['invoice_no'], name='invoices_invoice_079267_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['status', 'expires_at'], name='invoices_status_4792b1_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['transaction_ref'], name='payments_transac_ceca2e_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status'], name='payments_status_d621e5_idx'),
        ),
        migrations.AddIndex(
            model_name='policy',
            index=models.Index(fields=['policy_no'], name='policies_policy__b997dd_idx'),
        ),
        migrations.AddIndex(
            model_name='policy',
            index=models.Index(fields=['start_date', 'end_date'], name='policies_start_d_34ca2f_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['plate_no'], name='vehicles_plate_n_5072f8_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['user', '-created_at'], name='vehicles_user_id_50f588_idx'),
        ),
        migrations.AddIndex(
            model_name='insuranceorder',
            index=models.Index(fields=['user', '-created_at'], name='insurance_o_user_id_c198e5_idx'),
        ),
        migrations.AddIndex(
            model_name='insuranceorder',
            index=models.Index(fields=['status'], name='insurance_o_status_e2e25e_idx'),
        ),
        migrations.AddIndex(
            model_name='insuranceorder',
            index=models.Index(fields=['order_code'], name='insurance_o_order_c_5876a4_idx'),
        ),
    ]
