# Generated by Django 5.0 on 2026-01-19 21:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='insuranceservice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='insuranceservice',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='نشط'),
        ),
        migrations.AddField(
            model_name='insuranceservice',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
