# Generated by Django 5.0 on 2026-01-19 10:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15, unique=True, verbose_name='رقم الجوال')),
                ('whatsapp_id', models.CharField(max_length=100, verbose_name='معرف واتساب')),
                ('session_status', models.CharField(choices=[('active', 'نشط'), ('inactive', 'غير نشط'), ('blocked', 'محظور')], default='active', max_length=20, verbose_name='حالة الجلسة')),
                ('last_message_at', models.DateTimeField(auto_now=True, verbose_name='آخر رسالة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_sessions', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'جلسة واتساب',
                'verbose_name_plural': 'جلسات واتساب',
                'db_table': 'whatsapp_sessions',
                'ordering': ['-last_message_at'],
            },
        ),
    ]
