# Generated by Django 5.0 on 2026-01-19 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_integration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappsession',
            name='conversation_history',
            field=models.JSONField(blank=True, default=list, verbose_name='سجل المحادثة'),
        ),
        migrations.AlterField(
            model_name='whatsappsession',
            name='whatsapp_id',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='معرف واتساب'),
        ),
    ]
