# Generated by Django 5.0 on 2026-01-20 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_integration', '0002_whatsappsession_conversation_history_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappsession',
            name='context_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='بيانات السياق'),
        ),
        migrations.AddField(
            model_name='whatsappsession',
            name='conversation_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='معرف المحادثة'),
        ),
        migrations.AddField(
            model_name='whatsappsession',
            name='current_stage',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='المرحلة الحالية'),
        ),
    ]
